version: '2'
services:
  pg:
    image: postgres
  redis:
    image: redis
  backend:
    build: ./Backend
    ports:
     - "3000:3000"
    volumes:
     - .:/Backend
    depends_on:
     - redis
     -pg
    links:
      - pg
      -redis
    environment:
      - PGHOST=pg
      - PGDATABASE=postgres
      - PGUSER=lordvoldemort
